main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('waifus/', views.waifus_index, name='index'),
  path('waifus/<int:waifu_id>/', views.waifus_detail, name='detail'),
  path('waifus/create/', views.WaifuCreate.as_view(), name='waifus_create'),
  path('waifus/<int:pk>/update/', views.WaifuUpdate.as_view(), name='waifus_update'),
  path('waifus/<int:pk>/delete/', views.WaifuDelete.as_view(), name='waifus_delete'),
  path('waifus/<int:waifu_id>/add_cameo/', views.add_cameo, name='add_cameo'),
  
  path('waifus/<int:waifu_id>/assoc_accessory/<int:accessory_id>/', views.assoc_accessory, name='assoc_accessory'),
  path('waifus/<int:waifu_id>/unassoc_accessory/<int:accessory_id>/', views.unassoc_accessory, name='unassoc_accessory'),
#   path('waifus/<int:waifu_id>/add_photo/', views.add_photo, name='add_photo'),
  path('accessories/', views.AccessoryList.as_view(), name='accessories_index'),
  path('accessories/<int:pk>/', views.AccessoryDetail.as_view(), name='accessories_detail'),
  path('accessories/create/', views.AccessoryCreate.as_view(), name='accessories_create'),
  path('accessories/<int:pk>/update/', views.AccessoryUpdate.as_view(), name='accessories_update'),
  path('accessories/<int:pk>/delete/', views.AccessoryDelete.as_view(), name='accessories_delete'),

  path('waifus/<int:waifu_id>/add_photo/', views.add_photo, name='add_photo'),
]

waifucollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEDIUMS = (
    ("G", "Video Game"),
    ("B", "Book"),
    ("A", "Anime")
)

# A non specific item (e.g. a book) a waifu could own
class Accessory(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('accessories_detail', kwargs={'pk': self.id})

# Create your models here.
class Waifu(models.Model):
    name = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    accessories = models.ManyToManyField(Accessory)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("detail", kwargs={"waifu_id": self.id})

# A specific cameo a waifu has in a specific piece of media with a description of their role
class Cameo(models.Model):
    title = models.CharField(max_length=100)
    medium = models.CharField(
        max_length=1,
        choices=MEDIUMS,
        default="A"
        )
    description = models.TextField('Describe their Cameo here')

    waifu = models.ForeignKey(Waifu, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} a {self.get_medium_display()}"
    
    class Meta:
        ordering = ["title"]

class Photo(models.Model):
    url = models.CharField(max_length=200)
    waifu = models.ForeignKey(Waifu, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for waifu_id: {self.waifu_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Cameo

class CameoForm(ModelForm):
  class Meta:
    model = Cameo
    fields = ['title', 'medium', 'description']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

import uuid
import boto3
import os

from .models import Accessory, Waifu, Photo
from .forms import CameoForm

# Create your views here.

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def waifus_index(request):
  waifus = Waifu.objects.all()
  return render(request, 'waifus/index.html', { 'waifus': waifus })

def waifus_detail(request, waifu_id):
  waifu = Waifu.objects.get(id=waifu_id)
  accessoriesNull = Accessory.objects.exclude(id__in=waifu.accessories.all().values_list('id'))
  cameo_form = CameoForm()
  return render(request, 'waifus/detail.html', { 'waifu': waifu, 
  'cameo_form': cameo_form,
  'accessories': accessoriesNull })


class WaifuCreate(CreateView):
  model = Waifu
  fields = ['name', 'series', 'description'] 

class WaifuUpdate(UpdateView):
  model = Waifu
  fields = '__all__'

class WaifuDelete(DeleteView):
  model = Waifu
  success_url = '/waifus/'

def add_cameo(request, waifu_id):
  # create a ModelForm instance using the data in request.POST
  form = CameoForm(request.POST)
  waifu = Waifu.objects.get(id=waifu_id)
# validate the form
  if form.is_valid():
       # don't save the form to the db until it
    # has the waifu_id assigned
    new_cameo = form.save(commit=False)
    new_cameo.waifu_id = waifu_id
    new_cameo.save()
    return redirect('detail', waifu_id=waifu_id)

class AccessoryList(ListView):
  model = Accessory

class AccessoryDetail(DetailView):
  model = Accessory

class AccessoryCreate(CreateView):
  model = Accessory
  fields = '__all__'

class AccessoryUpdate(UpdateView):
  model = Accessory
  fields = ['name', 'color']

class AccessoryDelete(DeleteView):
  model = Accessory
  success_url = '/accessories/'

def assoc_accessory(request, waifu_id, accessory_id):
  Waifu.objects.get(id=waifu_id).accessories.add(waifu_id)
  return redirect('detail', waifu_id=waifu_id)

def unassoc_accessory(request, waifu_id, accessory_id):
  Waifu.objects.get(id=waifu_id).accessories.remove(accessory_id)
  return redirect('detail', waifu_id=waifu_id)

def add_photo(request, waifu_id):
  # photo-file will be the "name" attribute on the <input>
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # build a unique filename keeping the image's original extension
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, waifu_id=waifu_id)
    except:
      print('An error occurred uploading file to S3')
  return redirect('detail', waifu_id=waifu_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

  <h1>About the Waifu Collector</h1>
  <hr />
  <p>Hire the Waifu Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Waifu Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;WaifuCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'waifus_create'%}">Create</a></li>
          <li><a href="{% url 'index'%}">View All My Waifus</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">

    {% block content %}
    {% endblock %}

</main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Waifu Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to the home page!</h1>
<h2>Enjoy a random gif: <h2>

{% comment %} <a href="{% url 'index'%}"><img src="https://waifu.vercel.app/sfw/random" alt="Homepage IMG" width="100%"> </a>  {% endcomment %}

<a href="{% url 'index'%}"><img src="https://waifu.vercel.app/sfw/wink" alt="Homepage IMG" width="100%"> </a> 

{% endblock %}

main_app/templates/main_app/waifu_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Waifu</h1>
  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' waifu.id %}">Cancel</a>
  </form>
  <br>
  <a href="{% url 'detail' waifu.id %}">Cancel</a>

{% endblock %}

main_app/templates/main_app/waifu_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %} 
        <h1>Edit <span class="teal-text"> {{ object.name }}</h1>

  {% else %} 
        <h1>Add Waifu</h1>
  {% endif %}

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/waifus/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Waifu Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ waifu.name }}</span>
        <p>Series: {{ waifu.series }}</p>
        <p>Description: {{ waifu.description }}</p>
       
      </div>
      <div class="card-action">
        <a href="{% url 'waifus_update' waifu.id %}">Edit</a>
        <a href="{% url 'waifus_delete' waifu.id %}">Delete</a>
      </div>
    </div>
  
  
  {% for photo in waifu.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' waifu.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
    </form>
</div>

  <div class="col s6">
 <form action="{% url 'add_cameo' waifu.id %}" method="POST">
    {% csrf_token %}
    {{ cameo_form.as_p }}
    <input type="submit" class="btn" value="Add Cameo">
  </form>
    <table class="striped">
      <thead>
        <tr><th>Title</th><th>Medium</th></tr>
      </thead>
      <tbody>
        {% for cameo in waifu.cameo_set.all %}
          <tr>
            <td>{{cameo.title}}</td>
            <td>{{cameo.get_medium_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>

<div class="row">
  <div class="col s6">
    <h3>{{ waifu.name }}'s Accessories</h3>
    {% if waifu.accessories.count %}
      {% for accessory in waifu.accessories.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ accessory.color }}">{{ accessory.color }}</span> {{ accessory.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_accessory' waifu.id accessory.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Accessories :(</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Available Accessories</h3>
    {% if accessories.count %}
      {% for accessory in accessories.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ accessory.color }}">{{ accessory.color }}</span> {{ accessory.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_accessory' waifu.id accessory.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{waifu.name}} Already Has All Accessories Available</h5>
    {% endif %}
  </div>
</div>


<script>
  const selectEl = document.getElementById('id_medium');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/waifus/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Waifu List</h1>
{% for waifu in waifus %}
  <div class="card">
    <a href="{% url 'detail' waifu.id %}">
      <div class="card-content">
        <span class="card-title">{{ waifu.name }}</span>
        <p>Series: {{ waifu.series }}</p>
        <p>Description: {{ waifu.description }}</p>
      </div>
    </a>
  </div>

{% endfor %}
{% endblock %}